url: http://daftspunk.github.io/ui-docs/
coreurl: http://daftspunk.github.io/ui-docs/core/
compurl: http://daftspunk.github.io/ui-docs/components/
viewurl: http://daftspunk.github.io/ui-docs/views/
jsurl: http://daftspunk.github.io/ui-docs/assets/javascript/
cssurl: http://daftspunk.github.io/ui-docs/assets/css/
imageurl: http://daftspunk.github.io/ui-docs/assets/images/
